package daimanager;

import java.awt.Toolkit;
import java.awt.datatransfer.StringSelection;
import javax.swing.DefaultListModel;
import javax.swing.ListSelectionModel;
import pwgenerator.PasswordGenerator;


/**
 * PasswordGeneratorDialog.java
 * 
 * The password generator of the application
 * 
 * @author Andy Dunkel andy.dunkel"at"ekiwi.de
 * @author published under the terms and conditions of the
 *      GNU General Public License,
 *      for details see file gpl.txt in the distribution
 *      package of this software
 *
 */
public class PasswordGeneratorDialog extends javax.swing.JDialog {
    
    /** Creates new form PasswordGeneratorDialog */
    public PasswordGeneratorDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        listPasswords.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        //Create Model für List
        listPasswords.setModel(new DefaultListModel());
        
        //add popup to list
        listPasswords.setComponentPopupMenu(mnuPasswords);
        
        
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        mnuPasswords = new javax.swing.JPopupMenu();
        itemCopy = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        edtPasswordLength = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        edtPasswordCount = new javax.swing.JTextField();
        chkSpecialChars = new javax.swing.JCheckBox();
        chkNumbers = new javax.swing.JCheckBox();
        chkCapitals = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPasswords = new javax.swing.JList();
        btGenPW = new javax.swing.JButton();

        jButton1.setText("jButton1");

        itemCopy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/copy16.png"))); // NOI18N
        itemCopy.setText("Copy");
        itemCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyPassword(evt);
            }
        });
        mnuPasswords.add(itemCopy);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Password length");

        edtPasswordLength.setText("10");

        jLabel2.setText("How many passwords?");

        edtPasswordCount.setText("5");

        chkSpecialChars.setText("Include special characters");

        chkNumbers.setText("Include numbers");

        chkCapitals.setText("Include Captitals");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Passwords"));
        jPanel1.setToolTipText("");

        listPasswords.setFont(new java.awt.Font("Courier New", 0, 11));
        listPasswords.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listPasswords);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );

        btGenPW.setText("Generate Passwords");
        btGenPW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatePasswords(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btGenPW, javax.swing.GroupLayout.DEFAULT_SIZE, 375, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(edtPasswordCount)
                            .addComponent(edtPasswordLength, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkNumbers)
                            .addComponent(chkSpecialChars)
                            .addComponent(chkCapitals))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(chkSpecialChars)
                    .addComponent(edtPasswordLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(chkNumbers)
                    .addComponent(edtPasswordCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkCapitals)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btGenPW)
                .addGap(9, 9, 9)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Generate Passwords
     * @param evt
     */
    private void generatePasswords(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatePasswords
        PasswordGenerator pg = new PasswordGenerator();
        pg.setCapitalsAllowed(chkCapitals.isSelected());
        pg.setNumbersAllowed(chkNumbers.isSelected());
        pg.setSpecialCharsAllowed(chkSpecialChars.isSelected());
        
        ((DefaultListModel)listPasswords.getModel()).clear();
        
        Integer length = new Integer(edtPasswordLength.getText());
        Integer count = new Integer(edtPasswordCount.getText());
        
        for (int i = 0; i < count; i++)
        {
            DefaultListModel m = (DefaultListModel)listPasswords.getModel();
            String pw = pg.generatePassword(length);
            m.addElement(pw);
            System.out.println(pw);
        }
    }//GEN-LAST:event_generatePasswords

    private void copyPassword(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyPassword
        int indexSelected = listPasswords.getSelectedIndex();
        
        if (indexSelected != -1)
        {
            String value = (String)(((DefaultListModel)listPasswords.getModel()).getElementAt(indexSelected));
            
            StringSelection ss = new StringSelection(value);
            Toolkit.getDefaultToolkit().getSystemClipboard().setContents(ss, null);            
            
        }
    }//GEN-LAST:event_copyPassword
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PasswordGeneratorDialog dialog = new PasswordGeneratorDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btGenPW;
    private javax.swing.JCheckBox chkCapitals;
    private javax.swing.JCheckBox chkNumbers;
    private javax.swing.JCheckBox chkSpecialChars;
    private javax.swing.JTextField edtPasswordCount;
    private javax.swing.JTextField edtPasswordLength;
    private javax.swing.JMenuItem itemCopy;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listPasswords;
    private javax.swing.JPopupMenu mnuPasswords;
    // End of variables declaration//GEN-END:variables
    
}
