package daimanager;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 * SplashScreen.java
 * 
 * hmm?
 * 
 * @author Andy Dunkel andy.dunkel"at"ekiwi.de
 * @author published under the terms and conditions of the
 *      GNU General Public License,
 *      for details see file gpl.txt in the distribution
 *      package of this software
 *
 */
public class SplashScreen extends javax.swing.JFrame {
    
    /** Creates new form SplashScreen */
    public SplashScreen() {
        this.setUndecorated(true);   
        initComponents();         
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();        
        
        this.setLocation((dim.width - this.getSize().width) / 2,  (dim.height - this.getSize().height) / 2);        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/splash.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void showFor(int millis)
    {
        setVisible(true);
        try {
           Thread.sleep(millis);
        } catch (InterruptedException e) {
        }
        setVisible(false);        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    
}
